import { withPublicUrl } from '@/utils/public-url.ts'

/**
 * 所有战备的静态配置表，包含名称、图标与输入序列。
 */
export const StratagemSetting = [
  {
    name: 'airburst_rocket_launcher',
    icon: withPublicUrl('icons/stratagems/airburst_rocket_launcher.svg'),
    operation: [
      2,
      1,
      1,
      3,
      4,
    ],
  },
  {
    name: 'anti_materiel_rifle',
    icon: withPublicUrl('icons/stratagems/anti_materiel_rifle.svg'),
    operation: [
      2,
      3,
      4,
      1,
      2,
    ],
  },
  {
    name: 'anti_personnel_minefield',
    icon: withPublicUrl('icons/stratagems/anti_personnel_minefield.svg'),
    operation: [
      2,
      3,
      1,
      4,
    ],
  },
  {
    name: 'anti_tank_mines',
    icon: withPublicUrl('icons/stratagems/anti_tank_mines.svg'),
    operation: [
      2,
      3,
      1,
      1,
    ],
  },
  {
    name: 'arc_thrower',
    icon: withPublicUrl('icons/stratagems/arc_thrower.svg'),
    operation: [
      2,
      4,
      2,
      1,
      3,
      3,
    ],
  },
  {
    name: 'autocannon',
    icon: withPublicUrl('icons/stratagems/autocannon.svg'),
    operation: [
      2,
      3,
      2,
      1,
      1,
      4,
    ],
  },
  {
    name: 'autocannon_sentry',
    icon: withPublicUrl('icons/stratagems/autocannon_sentry.svg'),
    operation: [
      2,
      1,
      4,
      1,
      3,
      1,
    ],
  },
  {
    name: 'ballistic_shield_backpack',
    icon: withPublicUrl('icons/stratagems/ballistic_shield_backpack.svg'),
    operation: [
      2,
      3,
      2,
      2,
      1,
      3,
    ],
  },
  {
    name: 'commando',
    icon: withPublicUrl('icons/stratagems/commando.svg'),
    operation: [
      2,
      3,
      1,
      2,
      4,
    ],
  },
  {
    name: 'dark_fluid_vessel',
    icon: withPublicUrl('icons/stratagems/dark_fluid_vessel.svg'),
    operation: [
      1,
      3,
      4,
      2,
      1,
      1,
    ],
  },
  {
    name: 'eagle_110mm_rocket_pods',
    icon: withPublicUrl('icons/stratagems/eagle_110mm_rocket_pods.svg'),
    operation: [
      1,
      4,
      1,
      3,
    ],
  },
  {
    name: 'eagle_500kg_bomb',
    icon: withPublicUrl('icons/stratagems/eagle_500kg_bomb.svg'),
    operation: [
      1,
      4,
      2,
      2,
      2,
    ],
  },
  {
    name: 'eagle_airstrike',
    icon: withPublicUrl('icons/stratagems/eagle_airstrike.svg'),
    operation: [
      1,
      4,
      2,
      4,
    ],
  },
  {
    name: 'eagle_cluster_bomb',
    icon: withPublicUrl('icons/stratagems/eagle_cluster_bomb.svg'),
    operation: [
      1,
      4,
      2,
      2,
      4,
    ],
  },
  {
    name: 'eagle_napalm_airstrike',
    icon: withPublicUrl('icons/stratagems/eagle_napalm_airstrike.svg'),
    operation: [
      1,
      4,
      2,
      1,
    ],
  },
  {
    name: 'eagle_rearm',
    icon: withPublicUrl('icons/stratagems/eagle_rearm.svg'),
    operation: [
      1,
      1,
      3,
      1,
      4,
    ],
  },
  {
    name: 'eagle_smoke_strike',
    icon: withPublicUrl('icons/stratagems/eagle_smoke_strike.svg'),
    operation: [
      1,
      4,
      1,
      2,
    ],
  },
  {
    name: 'eagle_strafing_run',
    icon: withPublicUrl('icons/stratagems/eagle_strafing_run.svg'),
    operation: [
      1,
      4,
      4,
    ],
  },
  {
    name: 'emancipator_exosuit',
    icon: withPublicUrl('icons/stratagems/emancipator_exosuit.svg'),
    operation: [
      3,
      2,
      4,
      1,
      3,
      2,
      1,
    ],
  },
  {
    name: 'ems_mortar_sentry',
    icon: withPublicUrl('icons/stratagems/ems_mortar_sentry.svg'),
    operation: [
      2,
      1,
      4,
      2,
      4,
    ],
  },
  {
    name: 'expendable_anti_tank',
    icon: withPublicUrl('icons/stratagems/expendable_anti_tank.svg'),
    operation: [
      2,
      2,
      3,
      1,
      4,
    ],
  },
  {
    name: 'flamethrower',
    icon: withPublicUrl('icons/stratagems/flamethrower.svg'),
    operation: [
      2,
      3,
      1,
      2,
      1,
    ],
  },
  {
    name: 'gatling_sentry',
    icon: withPublicUrl('icons/stratagems/gatling_sentry.svg'),
    operation: [
      2,
      1,
      4,
      3,
    ],
  },
  {
    name: 'grenade_launcher',
    icon: withPublicUrl('icons/stratagems/grenade_launcher.svg'),
    operation: [
      2,
      3,
      1,
      3,
      2,
    ],
  },
  {
    name: 'guard_dog',
    icon: withPublicUrl('icons/stratagems/guard_dog.svg'),
    operation: [
      2,
      1,
      3,
      1,
      4,
      2,
    ],
  },
  {
    name: 'guard_dog_dog_breath',
    icon: withPublicUrl('icons/stratagems/guard_dog_dog_breath.svg'),
    operation: [
      2,
      1,
      3,
      1,
      4,
      1,
    ],
  },
  {
    name: 'guard_dog_rover',
    icon: withPublicUrl('icons/stratagems/guard_dog_rover.svg'),
    operation: [
      2,
      1,
      3,
      1,
      4,
      4,
    ],
  },
  {
    name: 'heavy_machine_gun',
    icon: withPublicUrl('icons/stratagems/heavy_machine_gun.svg'),
    operation: [
      2,
      3,
      1,
      2,
      2,
    ],
  },
  {
    name: 'hellbomb',
    icon: withPublicUrl('icons/stratagems/hellbomb.svg'),
    operation: [
      2,
      1,
      3,
      2,
      1,
      4,
      2,
      1,
    ],
  },
  {
    name: 'hive_breaker_drill',
    icon: withPublicUrl('icons/stratagems/hive_breaker_drill.svg'),
    operation: [
      3,
      1,
      2,
      4,
      2,
      2,
    ],
  },
  {
    name: 'hmg_emplacement',
    icon: withPublicUrl('icons/stratagems/hmg_emplacement.svg'),
    operation: [
      2,
      1,
      3,
      4,
      4,
      3,
    ],
  },
  {
    name: 'incendiary_mines',
    icon: withPublicUrl('icons/stratagems/incendiary_mines.svg'),
    operation: [
      2,
      3,
      3,
      2,
    ],
  },
  {
    name: 'jump_pack',
    icon: withPublicUrl('icons/stratagems/jump_pack.svg'),
    operation: [
      2,
      1,
      1,
      2,
      1,
    ],
  },
  {
    name: 'laser_cannon',
    icon: withPublicUrl('icons/stratagems/laser_cannon.svg'),
    operation: [
      2,
      3,
      2,
      1,
      3,
    ],
  },
  {
    name: 'machine_gun',
    icon: withPublicUrl('icons/stratagems/machine_gun.svg'),
    operation: [
      2,
      3,
      2,
      1,
      4,
    ],
  },
  {
    name: 'machine_gun_sentry',
    icon: withPublicUrl('icons/stratagems/machine_gun_sentry.svg'),
    operation: [
      2,
      1,
      4,
      4,
      1,
    ],
  },
  {
    name: 'mortar_sentry',
    icon: withPublicUrl('icons/stratagems/mortar_sentry.svg'),
    operation: [
      2,
      1,
      4,
      4,
      2,
    ],
  },
  {
    name: 'orbital_120mm_he_barrage',
    icon: withPublicUrl('icons/stratagems/orbital_120mm_he_barrage.svg'),
    operation: [
      4,
      4,
      2,
      3,
      4,
      2,
    ],
  },
  {
    name: 'orbital_380mm_he_barrage',
    icon: withPublicUrl('icons/stratagems/orbital_380mm_he_barrage.svg'),
    operation: [
      4,
      2,
      1,
      1,
      3,
      2,
      2,
    ],
  },
  {
    name: 'orbital_airburst_strike',
    icon: withPublicUrl('icons/stratagems/orbital_airburst_strike.svg'),
    operation: [
      4,
      4,
      4,
    ],
  },
  {
    name: 'orbital_ems_strike',
    icon: withPublicUrl('icons/stratagems/orbital_ems_strike.svg'),
    operation: [
      4,
      4,
      3,
      2,
    ],
  },
  {
    name: 'orbital_gas_strike',
    icon: withPublicUrl('icons/stratagems/orbital_gas_strike.svg'),
    operation: [
      4,
      4,
      2,
      4,
    ],
  },
  {
    name: 'orbital_gatling_barrage',
    icon: withPublicUrl('icons/stratagems/orbital_gatling_barrage.svg'),
    operation: [
      4,
      2,
      3,
      1,
      1,
    ],
  },
  {
    name: 'orbital_illumination_flare',
    icon: withPublicUrl('icons/stratagems/orbital_illumination_flare.svg'),
    operation: [
      4,
      4,
      3,
      3,
    ],
  },
  {
    name: 'orbital_laser',
    icon: withPublicUrl('icons/stratagems/orbital_laser.svg'),
    operation: [
      4,
      2,
      1,
      4,
      2,
    ],
  },
  {
    name: 'orbital_napalm_barrage',
    icon: withPublicUrl('icons/stratagems/orbital_napalm_barrage.svg'),
    operation: [
      4,
      4,
      2,
      3,
      4,
      1,
    ],
  },
  {
    name: 'orbital_precision_strike',
    icon: withPublicUrl('icons/stratagems/orbital_precision_strike.svg'),
    operation: [
      4,
      4,
      1,
    ],
  },
  {
    name: 'orbital_railcannon_strike',
    icon: withPublicUrl('icons/stratagems/orbital_railcannon_strike.svg'),
    operation: [
      4,
      1,
      2,
      2,
      4,
    ],
  },
  {
    name: 'orbital_smoke_strike',
    icon: withPublicUrl('icons/stratagems/orbital_smoke_strike.svg'),
    operation: [
      4,
      4,
      2,
      1,
    ],
  },
  {
    name: 'orbital_walking_barrage',
    icon: withPublicUrl('icons/stratagems/orbital_walking_barrage.svg'),
    operation: [
      4,
      2,
      4,
      2,
      4,
      2,
    ],
  },
  {
    name: 'patriot_exosuit',
    icon: withPublicUrl('icons/stratagems/patriot_exosuit.svg'),
    operation: [
      3,
      2,
      4,
      1,
      3,
      2,
      2,
    ],
  },
  {
    name: 'prospecting_drill',
    icon: withPublicUrl('icons/stratagems/prospecting_drill.svg'),
    operation: [
      2,
      2,
      3,
      4,
      2,
      2,
    ],
  },
  {
    name: 'quasar_cannon',
    icon: withPublicUrl('icons/stratagems/quasar_cannon.svg'),
    operation: [
      2,
      2,
      1,
      3,
      4,
    ],
  },
  {
    name: 'railgun',
    icon: withPublicUrl('icons/stratagems/railgun.svg'),
    operation: [
      2,
      4,
      2,
      1,
      3,
      4,
    ],
  },
  {
    name: 'recoilless_rifle',
    icon: withPublicUrl('icons/stratagems/recoilless_rifle.svg'),
    operation: [
      2,
      3,
      4,
      4,
      3,
    ],
  },
  {
    name: 'reinforce',
    icon: withPublicUrl('icons/stratagems/reinforce.svg'),
    operation: [
      1,
      2,
      4,
      3,
      1,
    ],
  },
  {
    name: 'resupply',
    icon: withPublicUrl('icons/stratagems/resupply.svg'),
    operation: [
      2,
      2,
      1,
      4,
    ],
  },
  {
    name: 'rocket_sentry',
    icon: withPublicUrl('icons/stratagems/rocket_sentry.svg'),
    operation: [
      2,
      1,
      4,
      4,
      3,
    ],
  },
  {
    name: 'seaf_artillery',
    icon: withPublicUrl('icons/stratagems/seaf_artillery.svg'),
    operation: [
      4,
      1,
      1,
      2,
    ],
  },
  {
    name: 'seismic_probe',
    icon: withPublicUrl('icons/stratagems/seismic_probe.svg'),
    operation: [
      1,
      1,
      3,
      4,
      2,
      2,
    ],
  },
  {
    name: 'shield_generator_pack',
    icon: withPublicUrl('icons/stratagems/shield_generator_pack.svg'),
    operation: [
      2,
      1,
      3,
      4,
      3,
      4,
    ],
  },
  {
    name: 'shield_generator_relay',
    icon: withPublicUrl('icons/stratagems/shield_generator_relay.svg'),
    operation: [
      2,
      2,
      3,
      4,
      3,
      4,
    ],
  },
  {
    name: 'sos_beacon',
    icon: withPublicUrl('icons/stratagems/sos_beacon.svg'),
    operation: [
      1,
      2,
      4,
      1,
    ],
  },
  {
    name: 'spear',
    icon: withPublicUrl('icons/stratagems/spear.svg'),
    operation: [
      2,
      2,
      1,
      2,
      2,
    ],
  },
  {
    name: 'stalwart',
    icon: withPublicUrl('icons/stratagems/stalwart.svg'),
    operation: [
      2,
      3,
      2,
      1,
      1,
      3,
    ],
  },
  {
    name: 'sterilizer',
    icon: withPublicUrl('icons/stratagems/sterilizer.svg'),
    operation: [
      2,
      3,
      1,
      2,
      3,
    ],
  },
  {
    name: 'super_earth_flag',
    icon: withPublicUrl('icons/stratagems/super_earth_flag.svg'),
    operation: [
      2,
      1,
      2,
      1,
    ],
  },
  {
    name: 'supply_pack',
    icon: withPublicUrl('icons/stratagems/supply_pack.svg'),
    operation: [
      2,
      3,
      2,
      1,
      1,
      2,
    ],
  },
  {
    name: 'tectonic_drill',
    icon: withPublicUrl('icons/stratagems/tectonic_drill.svg'),
    operation: [
      2,
      2,
      3,
      4,
      2,
      2,
    ],
  },
  {
    name: 'tesla_tower',
    icon: withPublicUrl('icons/stratagems/tesla_tower.svg'),
    operation: [
      2,
      1,
      4,
      1,
      3,
      4,
    ],
  },
  {
    name: 'upload_data',
    icon: withPublicUrl('icons/stratagems/upload_data.svg'),
    operation: [
      3,
      4,
      1,
      1,
      1,
    ],
  },
  {
    name: 'anti_tank_emplacement',
    icon: withPublicUrl('icons/stratagems/anti_tank_emplacement.svg'),
    operation: [
      2,
      1,
      3,
      4,
      4,
      4,
    ],
  },
  {
    name: 'directional_shield',
    icon: withPublicUrl('icons/stratagems/directional_shield.svg'),
    operation: [
      2,
      1,
      3,
      4,
      1,
      1,
    ],
  },
  {
    name: 'flame_sentry',
    icon: withPublicUrl('icons/stratagems/flame_sentry.svg'),
    operation: [
      2,
      1,
      4,
      2,
      1,
      1,
    ],
  },
  {
    name: 'Fast_Recon_Vehicle',
    icon: withPublicUrl('icons/stratagems/Fast_Recon_Vehicle.svg'),
    operation: [
      3,
      2,
      4,
      2,
      4,
      2,
      1,
    ],
  },
  {
    name: 'Gas_Mine',
    icon: withPublicUrl('icons/stratagems/Gas_Mine.svg'),
    operation: [
      2,
      3,
      3,
      4,
    ],
  },
  {
    name: 'WASP',
    icon: withPublicUrl('icons/stratagems/StA-X3_W.A.S.P_Launcher.svg'),
    operation: [
      2,
      2,
      1,
      2,
      4,
    ],
  },
  {
    name: 'grenadier_battlement',
    icon: withPublicUrl('icons/stratagems/grenadier_battlement.svg'),
    operation: [
      2,
      4,
      2,
      3,
      4,
    ],
  },
  {
    name: 'hellbomb_portable',
    icon: withPublicUrl('icons/stratagems/hellbomb_portable.svg'),
    operation: [
      2,
      4,
      1,
      1,
      1,
    ],
  },
  {
    name: 'hover_pack',
    icon: withPublicUrl('icons/stratagems/hover_pack.svg'),
    operation: [
      2,
      1,
      1,
      2,
      3,
      4,
    ],
  },
  {
    name: 'one_true_flag',
    icon: withPublicUrl('icons/stratagems/one_true_flag.svg'),
    operation: [
      2,
      3,
      4,
      4,
      1,
    ],
  },
] as const
